server:
  error:
    include-stacktrace: never

spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY:accesskey}
        secret-key: ${AWS_SECRET_KEY:secretkey}
      region:
        static: ${AWS_REGION:us-east-1}
  application:
    name: product-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://soat-rds-instance-ms-products.cyxjxfysr67a.us-east-1.rds.amazonaws.com:5432/soat}
    username: ${SPRING_DATASOURCE_USERNAME:soatadmin}
    password: ${SPRING_DATASOURCE_PASSWORD:123456789}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: ${DB_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    placeholder-replacement: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    try-it-out-enabled: true
    filter: true
    persist-authorization: true

management:
  endpoints:
    web:
      base-path: /
