apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - configmaps/product-service.yml
  - secrets/product-service.yml
  - deployments/product-service.yml
  - services/product-service.yml
  - hpa/product-service.yml