apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - configmaps/products-app.yml
  - secrets/products-app.yml
  - deployments/products-app.yml
  - services/products-app.yml
  - hpa/products-app.yml